name: Compile LaTeX document
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'America/Los_Angeles' # this doesn't seem to do anything :(

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        compiler: lualatex
      env:
        TZ: 'America/Los_Angeles' # this also doesn't seem to do anything :(

    - name: Commit PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add main.pdf
        git commit -m "Add generated PDF" -a || echo "No changes to commit"
        git push https://${{ secrets.PAT }}@github.com/dreeves/snakeeyes.git
